version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - minio
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
    restart: unless-stopped

  worker:
    build: .
    command: bun run src/queue/worker.ts
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sui_hackfest_db
    volumes:
      - sui_hackfest_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  sui_hackfest_db_data:
  redis_data:
  minio_data:
